FPL_URL = "https://fantasy.premierleague.com/drf/"
LOGIN_BASE_URL = "https://users.premierleague.com/"
LOGIN_SUBURL = "accounts/login/"
LEAGUE_H2H_STANDING_SUBURL = "leagues-h2h-standings/"
BOOTSTRAP = "bootstrap/" # (more data if authenticated)
PLAYERS_INFO_SUBURL = "elements/"
BOOTSTRAP_DYNAMIC_URL = "bootstrap-dynamic/"
GAMEWEEK_URL = "event/"
GAMEWEEKS_URL = "events/"
ELEMENT_SUMMARY_URL = "element-summary/"
ELEMENT_TYPES_URL = "element-types/"
FIXTURES_SUBURL = "fixtures/"
REGION_URL = "region/"
TRANSFERS_URL = "transfers/" # (requires auth)
ENTRY_BY_ID_URL = "entry/"
ENTRIES_URL = "entries/"
MY_TEAM_URL = "my-team/" # {team_id}(requires auth)
LEAGUES_ENTERED_URL = "leagues-entered/" # {teamId} (requires auth)
LEAGUES_CLASSIC_URL = "leagues-classic/" # {leagueId} # (must be a member)
LEAGUES_CLASSIC_STANDINGS_URL = "leagues-classic-standings/" # {leagueId}
LEAGUES_H2H_URL = "leagues-h2h/" # {leagueId} (must be a member)
LEAGUES_H2H_STANDINGS_URL = "leagues-h2h-standings/" # {leagueId}
LIVE_SUBURL = "/live"
PICKS_SUBURL = "/picks"
ENTRY_HISTORY_SUBURL = "/history"
