#!/usr/bin/env python
import os
from subprocess import check_call
import shutil


def run(command):
    return check_call(command, shell=True)


directory = os.path.dirname
REPO_DIR = directory(directory(os.path.abspath(__file__)))
os.chdir(REPO_DIR)

run('pip install -r requirements.txt')
run('pip install -r ci-requirements.txt')
if os.path.isdir('dist') and os.listdir('dist'):
    shutil.rmtree('dist')
run('python setup.py bdist_wheel')
wheel_dist = os.listdir('dist')[0]
run('pip install %s' % (os.path.join('dist', wheel_dist)))
