#!/usr/bin/env python
import os
from subprocess import check_call

directory = os.path.dirname

REPO_DIR = directory(directory(os.path.abspath(__file__)))
os.chdir(REPO_DIR)


def run(command):
    return check_call(command, shell=True)

run('nosetests -v tests/unit/')
